cxf:
  path: /
spring:
  application:
    name: oidc
catalina:
  home: .
security:
  basic:
    enabled: false
logging:
#  file: ${catalina.home}/logs/${spring.application.name}.log
  level:
    root: INFO
